name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: wajahatkarim3/Hugo-On-Fire@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

